'use strict';

// ── Image pool helper ────────────────────────────────────
const _B = 'https://images.unsplash.com/photo-';
const _Q = '?auto=format&fit=crop&q=80';
function _u(id, w, h) { return `${_B}${id}${_Q}&w=${w}&h=${h}`; }

// Raw photo IDs (re-used across product galleries)
const PH = {
  // Sarees
  s1: '1610030469983-98e550d6193c',
  s2: '1620916566398-39f1143ab7be',
  s3: '1515886657613-9f3515b0c78f',
  s4: '1583391733956-3750e0ff4e8b',
  // Kurtas & Suits
  k1: '1567401893414-76b7b1e5a7a5',
  k2: '1572804013427-4d7ca7268217',
  k3: '1521572163474-6864f9cf17ab',
  k4: '1617627143750-d86bc21e42bb',
  // Lehengas
  l1: '1625401029636-da0e7a24ee3b',
  l2: '1617206494559-ef0a585d4d17',
  l3: '1539109136881-3be0616acf4b',
  l4: '1594938298603-c8148c4b4b2f',
  // Indo-Western
  iw1: '1485518994671-4b02bb87a49f',
  iw2: '1441984904996-e0b6ba687e04',
  iw3: '1469334031218-e382a71b716b',
  iw4: '1529139574466-a303027c1d8b',
};

// Build image arrays  [large, large, large, large]  +  [thumb, thumb, thumb, thumb]
function imgs(a, b, c, d) {
  const ids = [a, b, c, d];
  return {
    images: ids.map(id => _u(id, 800, 1000)),
    thumbs: ids.map(id => _u(id, 200, 250)),
  };
}

// ── Product catalogue ────────────────────────────────────
window.PRODUCTS = [
  {
    id: 1,
    name: 'Royal Blue Kanjivaram Silk Saree',
    category: 'sarees', categoryLabel: 'Sarees',
    price: 6999, originalPrice: 9500,
    badge: 'new', badgeLabel: 'New',
    rating: 5, reviews: 128,
    sku: 'ANY-SAR-001',
    fabric: 'Pure Kanjivaram Silk',
    occasion: 'Wedding, Festival, Formal',
    inStock: true,
    colors: [
      { hex: '#1B3A8C', name: 'Royal Blue' },
      { hex: '#7B1A3A', name: 'Burgundy' },
      { hex: '#2D6A4F', name: 'Emerald' },
    ],
    sizes: ['Free Size'],
    images: ['image/products/silksaari.jpg'],
    thumbs: ['image/products/silksaari.jpg'],
    description: 'A timeless masterpiece crafted from the finest Kanjivaram silk, this saree features intricate zari weaving and a rich royal blue hue that exudes royalty. The contrast golden border and pallu make it perfect for weddings and grand festivities. Each piece is handwoven by master weavers from Kanchipuram, preserving centuries of tradition in every thread.',
    care: ['Dry clean only', 'Store wrapped in a muslin cloth', 'Avoid direct sunlight', 'Do not wring or squeeze', 'Iron on low heat from the reverse side'],
    delivery: 'Free delivery within 3–5 business days',
  },
  {
    id: 2,
    name: 'Crimson Embroidered Georgette Saree',
    category: 'sarees', categoryLabel: 'Sarees',
    price: 4499, originalPrice: null,
    badge: null, badgeLabel: null,
    rating: 4, reviews: 87,
    sku: 'ANY-SAR-002',
    fabric: 'Premium Georgette',
    occasion: 'Party, Festive, Casual',
    inStock: true,
    colors: [
      { hex: '#C0392B', name: 'Crimson' },
      { hex: '#1B3A8C', name: 'Royal Blue' },
      { hex: '#2C3E50', name: 'Midnight' },
    ],
    sizes: ['Free Size'],
    images: ['image/products/crimsonsaari.jpg'],
    thumbs: ['image/products/crimsonsaari.jpg'],
    description: 'Draped in elegance, this crimson georgette saree is adorned with delicate thread embroidery across the body and a statement embellished border. The lightweight fabric ensures ease of movement while the vibrant colour commands attention at any celebration.',
    care: ['Dry clean recommended', 'Store in a cool, dry place', 'Avoid contact with perfume directly on fabric', 'Iron on low heat'],
    delivery: 'Free delivery within 3–5 business days',
  },
  {
    id: 3,
    name: 'Golden Banarasi Zari Silk Saree',
    category: 'sarees', categoryLabel: 'Sarees',
    price: 7999, originalPrice: 12000,
    badge: 'sale', badgeLabel: 'Sale',
    rating: 5, reviews: 215,
    sku: 'ANY-SAR-003',
    fabric: 'Pure Banarasi Silk',
    occasion: 'Bridal, Wedding, Festival',
    inStock: true,
    colors: [
      { hex: '#C9A84C', name: 'Antique Gold' },
      { hex: '#8B0000', name: 'Deep Red' },
      { hex: '#1A3B5D', name: 'Peacock Blue' },
    ],
    sizes: ['Free Size'],
    images: ['image/products/goldensaari.jpg'],
    thumbs: ['image/products/goldensaari.jpg'],
    description: 'Woven in the holy city of Varanasi, this exquisite Banarasi silk saree showcases rich zari work with motifs inspired by Mughal architecture. The heavy golden border and intricate weaving make it an heirloom-worthy piece, perfect for brides and grand celebrations.',
    care: ['Dry clean only', 'Store in a cool, dark place wrapped in muslin', 'Never fold on the zari work', 'Keep away from moisture'],
    delivery: 'Free delivery within 3–5 business days',
  },
  {
    id: 4,
    name: 'Ivory Chikankari Kurta Palazzo Set',
    category: 'kurtas', categoryLabel: 'Kurtas & Suits',
    price: 3299, originalPrice: 4500,
    badge: 'new', badgeLabel: 'New',
    rating: 4, reviews: 64,
    sku: 'ANY-KUR-001',
    fabric: 'Cotton Mulmul',
    occasion: 'Casual, Work, Festive',
    inStock: true,
    colors: [
      { hex: '#F8F2E6', name: 'Ivory' },
      { hex: '#F4C2C2', name: 'Blush' },
      { hex: '#D8B4FE', name: 'Lavender' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    images: ['image/products/ivorryset.jpg'],
    thumbs: ['image/products/ivorryset.jpg'],
    description: 'Effortlessly elegant, this ivory Chikankari kurta palazzo set is a celebration of Lucknow\'s finest hand-embroidery tradition. The breathable cotton mulmul fabric is perfect for all-day wear, while the delicate white-on-white thread work adds a timeless charm to your ethnic wardrobe.',
    care: ['Machine wash on gentle cycle', 'Use mild detergent only', 'Do not bleach', 'Iron on medium heat', 'Dry in shade'],
    delivery: 'Free delivery within 3–5 business days',
  },
  {
    id: 5,
    name: 'Emerald Embroidered Anarkali Suit',
    category: 'kurtas', categoryLabel: 'Kurtas & Suits',
    price: 5499, originalPrice: null,
    badge: null, badgeLabel: null,
    rating: 5, reviews: 102,
    sku: 'ANY-KUR-002',
    fabric: 'Georgette with Net Dupatta',
    occasion: 'Party, Festive, Semi-formal',
    inStock: true,
    colors: [
      { hex: '#2D6A4F', name: 'Emerald' },
      { hex: '#7B1A3A', name: 'Maroon' },
      { hex: '#E9C46A', name: 'Mustard' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    images: ['image/products/anarkalidress.jpg'],
    thumbs: ['image/products/anarkalidress.jpg'],
    description: 'Make a grand entrance in this stunning emerald green Anarkali suit, crafted from premium georgette and embellished with intricate thread and sequin embroidery. The floor-sweeping silhouette paired with a matching net dupatta creates an unforgettable festive look.',
    care: ['Dry clean recommended', 'Hand wash net dupatta separately', 'Iron on low heat with protective cloth', 'Store on a hanger to avoid creasing'],
    delivery: 'Free delivery within 3–5 business days',
  },
  {
    id: 6,
    name: 'Royal Cream Silk Sherwani Set',
    category: 'kurtas', categoryLabel: 'Kurtas & Suits',
    price: 14999, originalPrice: 20000,
    badge: 'men', badgeLabel: "Men's",
    rating: 4, reviews: 49,
    sku: 'ANY-KUR-003',
    fabric: 'Silk Blend with Brocade',
    occasion: 'Wedding, Festive, Formal',
    inStock: true,
    colors: [
      { hex: '#F5ECD7', name: 'Ivory' },
      { hex: '#1A1825', name: 'Midnight' },
      { hex: '#4A3728', name: 'Charcoal Brown' },
    ],
    sizes: ['38', '40', '42', '44', '46', '48'],
    images: ['image/products/sherwani.jpg'],
    thumbs: ['image/products/sherwani.jpg'],
    description: 'Crafted for the modern groom and gentleman, this royal cream sherwani set combines traditional craftsmanship with contemporary tailoring. The silk blend fabric is adorned with subtle brocade patterns and the set includes a kurta, churidar, and embroidered dupatta.',
    care: ['Dry clean only', 'Store in a garment bag', 'Press lightly with a cloth between iron and fabric', 'Avoid hanging for extended periods'],
    delivery: 'Free delivery within 3–5 business days',
  },
  {
    id: 7,
    name: 'Scarlet Bridal Lehenga Choli',
    category: 'lehengas', categoryLabel: 'Lehengas',
    price: 24999, originalPrice: 35000,
    badge: 'new', badgeLabel: 'New',
    rating: 5, reviews: 176,
    sku: 'ANY-LEH-001',
    fabric: 'Raw Silk with Net Dupatta',
    occasion: 'Wedding, Bridal, Engagement',
    inStock: true,
    colors: [
      { hex: '#C0392B', name: 'Scarlet' },
      { hex: '#F4A460', name: 'Peach' },
      { hex: '#C9A8B2', name: 'Dusty Rose' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    images: ['image/products/lehanga.jpg'],
    thumbs: ['image/products/lehanga.jpg'],
    description: 'Every bride deserves to feel extraordinary on her special day. This scarlet bridal lehenga choli features dense zardozi embroidery with real gold and silver threads, paired with a heavily embellished choli and a gorgeous net dupatta. A custom fit option is available to ensure a perfect silhouette.',
    care: ['Dry clean only by a specialist', 'Store flat in a breathable garment bag', 'Avoid contact with sharp jewellery', 'Do not expose to strong light for extended periods'],
    delivery: 'Free delivery within 5–7 business days. Custom orders take 15–20 days.',
  },
  {
    id: 8,
    name: 'Blush Pink Organza Lehenga Set',
    category: 'lehengas', categoryLabel: 'Lehengas',
    price: 16499, originalPrice: null,
    badge: null, badgeLabel: null,
    rating: 4, reviews: 93,
    sku: 'ANY-LEH-002',
    fabric: 'Pure Organza Silk',
    occasion: 'Wedding Guest, Festive, Reception',
    inStock: true,
    colors: [
      { hex: '#FFB6C1', name: 'Blush Pink' },
      { hex: '#F5ECD7', name: 'Ivory' },
      { hex: '#E0B4D4', name: 'Lilac' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    images: ['image/products/pinksaari.jpg'],
    thumbs: ['image/products/pinksaari.jpg'],
    description: 'Delicately crafted from pure organza silk, this blush pink lehenga set exudes feminine grace and sophistication. The hand-painted floral motifs and scalloped border are complemented by a fitted choli with mirror work, creating a dreamy look for weddings and festive occasions.',
    care: ['Dry clean only', 'Store in a muslin bag to prevent yellowing', 'Avoid wringing or squeezing', 'Iron on the lowest heat setting with a pressing cloth'],
    delivery: 'Free delivery within 3–5 business days',
  },
  {
    id: 9,
    name: 'Teal Mirror Work Lehenga',
    category: 'lehengas', categoryLabel: 'Lehengas',
    price: 13999, originalPrice: 19500,
    badge: 'sale', badgeLabel: 'Sale',
    rating: 5, reviews: 58,
    sku: 'ANY-LEH-003',
    fabric: 'Velvet with Mirror Embroidery',
    occasion: 'Festive, Sangeet, Navratri',
    inStock: true,
    colors: [
      { hex: '#008080', name: 'Teal' },
      { hex: '#2C3E6B', name: 'Indigo' },
      { hex: '#B7410E', name: 'Rust' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'Custom'],
    images: ['image/products/teel.jpg'],
    thumbs: ['image/products/teel.jpg'],
    description: 'Inspired by the vibrant craft traditions of Rajasthan, this teal velvet lehenga is adorned with hundreds of hand-stitched mirrors and intricate embroidery. It catches light beautifully with every movement, making it the perfect showstopper for Sangeet nights and festive gatherings.',
    care: ['Dry clean only', 'Avoid direct sunlight to preserve mirror work', 'Store flat in a cool, dry place', 'Handle with care — mirrors are delicate'],
    delivery: 'Free delivery within 3–5 business days',
  },
  {
    id: 10,
    name: 'Embellished Indo-Western Crop Set',
    category: 'indo-western', categoryLabel: 'Indo-Western',
    price: 4999, originalPrice: null,
    badge: 'new', badgeLabel: 'New',
    rating: 4, reviews: 41,
    sku: 'ANY-IW-001',
    fabric: 'Chanderi Silk',
    occasion: 'Party, Office Festive, Casual',
    inStock: true,
    colors: [
      { hex: '#F7E7CE', name: 'Champagne' },
      { hex: '#C9A8B2', name: 'Rose Gold' },
      { hex: '#C0C0C0', name: 'Silver' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: ['image/products/indowester.jpg'],
    thumbs: ['image/products/indowester.jpg'],
    description: 'Bridging the gap between traditional charm and modern style, this embellished crop top and palazzo set is crafted from luxurious Chanderi silk. The top features a delicate sequin pattern while the wide-leg palazzo flows beautifully. A versatile piece that works for office Diwali parties and evening events alike.',
    care: ['Hand wash in cold water', 'Use gentle detergent', 'Do not tumble dry', 'Iron on low heat', 'Dry in shade'],
    delivery: 'Free delivery within 3–5 business days',
  },
  {
    id: 11,
    name: 'Printed Palazzo Co-ord Set',
    category: 'indo-western', categoryLabel: 'Indo-Western',
    price: 3799, originalPrice: 5000,
    badge: null, badgeLabel: null,
    rating: 4, reviews: 73,
    sku: 'ANY-IW-002',
    fabric: 'Rayon Crepe',
    occasion: 'Casual, Travel, Brunch',
    inStock: true,
    colors: [
      { hex: '#FF7F7F', name: 'Coral' },
      { hex: '#008080', name: 'Teal' },
      { hex: '#6B8E23', name: 'Olive' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: ['image/products/plazoset.jpg'],
    thumbs: ['image/products/plazoset.jpg'],
    description: 'This effortlessly chic printed palazzo co-ord set is your perfect travel and brunch companion. Made from breathable rayon crepe with a gorgeous block-print inspired pattern, the coordinated top and palazzo look put-together yet feel incredibly comfortable throughout the day.',
    care: ['Machine wash on gentle cycle', 'Cold water only', 'Do not bleach', 'Dry in shade', 'Cool iron'],
    delivery: 'Free delivery within 3–5 business days',
  },
  {
    id: 12,
    name: 'Floral Embroidered Ethnic Gown',
    category: 'indo-western', categoryLabel: 'Indo-Western',
    price: 6499, originalPrice: 8999,
    badge: 'sale', badgeLabel: 'Sale',
    rating: 5, reviews: 89,
    sku: 'ANY-IW-003',
    fabric: 'Georgette with Sequin Work',
    occasion: 'Party, Reception, Festive',
    inStock: true,
    colors: [
      { hex: '#6B0F1A', name: 'Wine' },
      { hex: '#556B2F', name: 'Olive' },
      { hex: '#1B3A8C', name: 'Cobalt Blue' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    images: ['image/products/ethnicgown.jpg'],
    thumbs: ['image/products/ethnicgown.jpg'],
    description: 'A stunning fusion of Indian embroidery and Western silhouettes, this floor-length ethnic gown features delicate floral sequin embroidery on a rich georgette base. The A-line cut is universally flattering, and the subtle slit adds an element of modern elegance. Perfect for receptions and evening parties.',
    care: ['Dry clean recommended', 'Handle sequin work gently', 'Store on a padded hanger', 'Iron inside out on low heat'],
    delivery: 'Free delivery within 3–5 business days',
  },
];
